/* SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Copyright:
 *   2020      Evan Nemerson <evan@nemerson.com>
 */

#if !defined(SIMDE_ARM_NEON_H)
#define SIMDE_ARM_NEON_H

#include "src/simde/simde/arm/neon/types.h"

#include "src/simde/simde/arm/neon/aba.h"
#include "src/simde/simde/arm/neon/abd.h"
#include "src/simde/simde/arm/neon/abdl.h"
#include "src/simde/simde/arm/neon/abs.h"
#include "src/simde/simde/arm/neon/add.h"
#include "src/simde/simde/arm/neon/addhn.h"
#include "src/simde/simde/arm/neon/addl.h"
#include "src/simde/simde/arm/neon/addlv.h"
#include "src/simde/simde/arm/neon/addl_high.h"
#include "src/simde/simde/arm/neon/addv.h"
#include "src/simde/simde/arm/neon/addw.h"
#include "src/simde/simde/arm/neon/addw_high.h"
#include "src/simde/simde/arm/neon/and.h"
#include "src/simde/simde/arm/neon/bcax.h"
#include "src/simde/simde/arm/neon/bic.h"
#include "src/simde/simde/arm/neon/bsl.h"
#include "src/simde/simde/arm/neon/cage.h"
#include "src/simde/simde/arm/neon/cagt.h"
#include "src/simde/simde/arm/neon/ceq.h"
#include "src/simde/simde/arm/neon/ceqz.h"
#include "src/simde/simde/arm/neon/cge.h"
#include "src/simde/simde/arm/neon/cgez.h"
#include "src/simde/simde/arm/neon/cgt.h"
#include "src/simde/simde/arm/neon/cgtz.h"
#include "src/simde/simde/arm/neon/cle.h"
#include "src/simde/simde/arm/neon/clez.h"
#include "src/simde/simde/arm/neon/cls.h"
#include "src/simde/simde/arm/neon/clt.h"
#include "src/simde/simde/arm/neon/cltz.h"
#include "src/simde/simde/arm/neon/clz.h"
#include "src/simde/simde/arm/neon/cmla.h"
#include "src/simde/simde/arm/neon/cmla_rot90.h"
#include "src/simde/simde/arm/neon/cmla_rot180.h"
#include "src/simde/simde/arm/neon/cmla_rot270.h"
#include "src/simde/simde/arm/neon/cnt.h"
#include "src/simde/simde/arm/neon/cvt.h"
#include "src/simde/simde/arm/neon/cvtn.h"
#include "src/simde/simde/arm/neon/combine.h"
#include "src/simde/simde/arm/neon/create.h"
#include "src/simde/simde/arm/neon/dot.h"
#include "src/simde/simde/arm/neon/dot_lane.h"
#include "src/simde/simde/arm/neon/dup_lane.h"
#include "src/simde/simde/arm/neon/dup_n.h"
#include "src/simde/simde/arm/neon/eor.h"
#include "src/simde/simde/arm/neon/ext.h"
#include "src/simde/simde/arm/neon/fma.h"
#include "src/simde/simde/arm/neon/fma_lane.h"
#include "src/simde/simde/arm/neon/fma_n.h"
#include "src/simde/simde/arm/neon/get_high.h"
#include "src/simde/simde/arm/neon/get_lane.h"
#include "src/simde/simde/arm/neon/get_low.h"
#include "src/simde/simde/arm/neon/hadd.h"
#include "src/simde/simde/arm/neon/hsub.h"
#include "src/simde/simde/arm/neon/ld1.h"
#include "src/simde/simde/arm/neon/ld1_dup.h"
#include "src/simde/simde/arm/neon/ld1_lane.h"
#include "src/simde/simde/arm/neon/ld1_x2.h"
#include "src/simde/simde/arm/neon/ld1_x3.h"
#include "src/simde/simde/arm/neon/ld1_x4.h"
#include "src/simde/simde/arm/neon/ld1q_x2.h"
#include "src/simde/simde/arm/neon/ld1q_x3.h"
#include "src/simde/simde/arm/neon/ld1q_x4.h"
#include "src/simde/simde/arm/neon/ld2.h"
#include "src/simde/simde/arm/neon/ld3.h"
#include "src/simde/simde/arm/neon/ld4.h"
#include "src/simde/simde/arm/neon/ld4_lane.h"
#include "src/simde/simde/arm/neon/max.h"
#include "src/simde/simde/arm/neon/maxnm.h"
#include "src/simde/simde/arm/neon/maxv.h"
#include "src/simde/simde/arm/neon/min.h"
#include "src/simde/simde/arm/neon/minnm.h"
#include "src/simde/simde/arm/neon/minv.h"
#include "src/simde/simde/arm/neon/mla.h"
#include "src/simde/simde/arm/neon/mla_lane.h"
#include "src/simde/simde/arm/neon/mla_n.h"
#include "src/simde/simde/arm/neon/mlal.h"
#include "src/simde/simde/arm/neon/mlal_high.h"
#include "src/simde/simde/arm/neon/mlal_high_n.h"
#include "src/simde/simde/arm/neon/mlal_lane.h"
#include "src/simde/simde/arm/neon/mlal_n.h"
#include "src/simde/simde/arm/neon/mls.h"
#include "src/simde/simde/arm/neon/mls_n.h"
#include "src/simde/simde/arm/neon/mlsl.h"
#include "src/simde/simde/arm/neon/mlsl_high.h"
#include "src/simde/simde/arm/neon/mlsl_high_n.h"
#include "src/simde/simde/arm/neon/mlsl_lane.h"
#include "src/simde/simde/arm/neon/mlsl_n.h"
#include "src/simde/simde/arm/neon/movl.h"
#include "src/simde/simde/arm/neon/movl_high.h"
#include "src/simde/simde/arm/neon/movn.h"
#include "src/simde/simde/arm/neon/movn_high.h"
#include "src/simde/simde/arm/neon/mul.h"
#include "src/simde/simde/arm/neon/mul_lane.h"
#include "src/simde/simde/arm/neon/mul_n.h"
#include "src/simde/simde/arm/neon/mull.h"
#include "src/simde/simde/arm/neon/mull_high.h"
#include "src/simde/simde/arm/neon/mull_lane.h"
#include "src/simde/simde/arm/neon/mull_n.h"
#include "src/simde/simde/arm/neon/mvn.h"
#include "src/simde/simde/arm/neon/neg.h"
#include "src/simde/simde/arm/neon/orn.h"
#include "src/simde/simde/arm/neon/orr.h"
#include "src/simde/simde/arm/neon/padal.h"
#include "src/simde/simde/arm/neon/padd.h"
#include "src/simde/simde/arm/neon/paddl.h"
#include "src/simde/simde/arm/neon/pmax.h"
#include "src/simde/simde/arm/neon/pmin.h"
#include "src/simde/simde/arm/neon/qabs.h"
#include "src/simde/simde/arm/neon/qadd.h"
#include "src/simde/simde/arm/neon/qdmulh.h"
#include "src/simde/simde/arm/neon/qdmulh_lane.h"
#include "src/simde/simde/arm/neon/qdmulh_n.h"
#include "src/simde/simde/arm/neon/qdmull.h"
#include "src/simde/simde/arm/neon/qrdmulh.h"
#include "src/simde/simde/arm/neon/qrdmulh_lane.h"
#include "src/simde/simde/arm/neon/qrdmulh_n.h"
#include "src/simde/simde/arm/neon/qrshrn_n.h"
#include "src/simde/simde/arm/neon/qrshrun_n.h"
#include "src/simde/simde/arm/neon/qmovn.h"
#include "src/simde/simde/arm/neon/qmovun.h"
#include "src/simde/simde/arm/neon/qmovn_high.h"
#include "src/simde/simde/arm/neon/qneg.h"
#include "src/simde/simde/arm/neon/qsub.h"
#include "src/simde/simde/arm/neon/qshl.h"
#include "src/simde/simde/arm/neon/qshlu_n.h"
#include "src/simde/simde/arm/neon/qshrn_n.h"
#include "src/simde/simde/arm/neon/qshrun_n.h"
#include "src/simde/simde/arm/neon/qtbl.h"
#include "src/simde/simde/arm/neon/qtbx.h"
#include "src/simde/simde/arm/neon/rbit.h"
#include "src/simde/simde/arm/neon/recpe.h"
#include "src/simde/simde/arm/neon/recps.h"
#include "src/simde/simde/arm/neon/reinterpret.h"
#include "src/simde/simde/arm/neon/rev16.h"
#include "src/simde/simde/arm/neon/rev32.h"
#include "src/simde/simde/arm/neon/rev64.h"
#include "src/simde/simde/arm/neon/rhadd.h"
#include "src/simde/simde/arm/neon/rnd.h"
#include "src/simde/simde/arm/neon/rndm.h"
#include "src/simde/simde/arm/neon/rndi.h"
#include "src/simde/simde/arm/neon/rndn.h"
#include "src/simde/simde/arm/neon/rndp.h"
#include "src/simde/simde/arm/neon/rshl.h"
#include "src/simde/simde/arm/neon/rshr_n.h"
#include "src/simde/simde/arm/neon/rshrn_n.h"
#include "src/simde/simde/arm/neon/rsqrte.h"
#include "src/simde/simde/arm/neon/rsqrts.h"
#include "src/simde/simde/arm/neon/rsra_n.h"
#include "src/simde/simde/arm/neon/set_lane.h"
#include "src/simde/simde/arm/neon/shl.h"
#include "src/simde/simde/arm/neon/shl_n.h"
#include "src/simde/simde/arm/neon/shll_n.h"
#include "src/simde/simde/arm/neon/shr_n.h"
#include "src/simde/simde/arm/neon/shrn_n.h"
#include "src/simde/simde/arm/neon/sqadd.h"
#include "src/simde/simde/arm/neon/sra_n.h"
#include "src/simde/simde/arm/neon/sri_n.h"
#include "src/simde/simde/arm/neon/st1.h"
#include "src/simde/simde/arm/neon/st1_lane.h"
#include "src/simde/simde/arm/neon/st2.h"
#include "src/simde/simde/arm/neon/st2_lane.h"
#include "src/simde/simde/arm/neon/st3.h"
#include "src/simde/simde/arm/neon/st3_lane.h"
#include "src/simde/simde/arm/neon/st4.h"
#include "src/simde/simde/arm/neon/st4_lane.h"
#include "src/simde/simde/arm/neon/sub.h"
#include "src/simde/simde/arm/neon/subhn.h"
#include "src/simde/simde/arm/neon/subl.h"
#include "src/simde/simde/arm/neon/subl_high.h"
#include "src/simde/simde/arm/neon/subw.h"
#include "src/simde/simde/arm/neon/subw_high.h"
#include "src/simde/simde/arm/neon/tbl.h"
#include "src/simde/simde/arm/neon/tbx.h"
#include "src/simde/simde/arm/neon/trn.h"
#include "src/simde/simde/arm/neon/trn1.h"
#include "src/simde/simde/arm/neon/trn2.h"
#include "src/simde/simde/arm/neon/tst.h"
#include "src/simde/simde/arm/neon/uqadd.h"
#include "src/simde/simde/arm/neon/uzp.h"
#include "src/simde/simde/arm/neon/uzp1.h"
#include "src/simde/simde/arm/neon/uzp2.h"
#include "src/simde/simde/arm/neon/xar.h"
#include "src/simde/simde/arm/neon/zip.h"
#include "src/simde/simde/arm/neon/zip1.h"
#include "src/simde/simde/arm/neon/zip2.h"

#endif /* SIMDE_ARM_NEON_H */
